version: "3.7"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:10.6-alpine
    volumes:
      # We'll store the postgres data in the 'postgres_data' volume we defined:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  # See https://docs.docker.com/compose/extends/#understanding-multiple-compose-files
