default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432') %>

development:
  <<: *default
  database: stoia_development

test:
  <<: *default
  database: stoia_test

production:
  <<: *default
  database: stoia_production
  username: stoia
  password: <%= ENV['STOIA_DATABASE_PASSWORD'] %>
